#!/usr/local/bin/python3

# ^ Python 3 path is absolute so that this works when run inside a virtualenv
# using a pre-3.7 Python.

import sys

from subprocess import CalledProcessError, run

# Make sure we only run this on the master branch, otherwise we'd most likely
# end up deleting "master" if run on a topic branch.
try:
    run(["git", "checkout", "--quiet", "master"], check=True)
except CalledProcessError:
    print(f"Could not switch to master branch")
    sys.exit(1)

# Delete all branches that are cleanly merged into master. Other branches may
# require rebasing.
merged_branches = run(
    ["git", "branch", "--merged"], capture_output=True, text=True
).stdout.split("\n")
merged_branches = [b.strip() for b in merged_branches]
merged_branches = [b for b in merged_branches if b and not b.startswith("*")]

for branch in merged_branches:
    try:
        # nb. This will print the branch name and commit hash, so we don't need
        # to do that ourselves.
        run(["git", "branch", "--delete", branch], check=True)
    except CalledProcessError:
        print(f"Could not delete {branch} automatically")
